config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticated do
    root to: "categories#index", as: :authenticated_user
  end

  root to: "splash#index", as: :unauthenticated_user

  resources :categories, only: [:index, :show, :new, :create] do
    resources :transactions, only: [:index]
  end
  resources :transactions, only: [:new, :create]
end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :transactions
  validates :name, :icon, presence: true

  def category_total_amount
    transactions.sum(:amount)
  end

  def category_recent_transactions
    transactions.order(updated_at: :desc)
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :category
  validates :name, :category, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :transactions
  validates :f_name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.where(author: current_user)
  end

  def show
    @category = Category.find(params[:category_id])
  end

  def new
    @category = Category.new
    respond_to do |format|
      format.html { render :new, locals: { category: @category } }
    end
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      format.html do
        if @category.save
          flash[:sucess] = 'Category Saved Successfully'
          redirect_to categories_path
        else
          flash.now[:error] = 'Error: The New Category could not be saved'
          render :new, locals: { category: @category }
        end
      end
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon).merge(author: current_user)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @category = Category.includes(:transactions).find(params[:category_id])
    @transactions = @category.category_recent_transactions
  end

  def new
    @categories = Category.where(author: current_user)
    @transaction = Transaction.new
    respond_to do |format|
      format.html { render :new, locals: { transaction: @transaction } }
    end
  end

  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      format.html do
        if @transaction.save
          flash[:sucess] = 'transaction Saved Successfully'
          redirect_to categories_path
        else
          flash.now[:error] = 'Error: The New transaction could not be saved'
          render :new, locals: { transaction: @transaction }
        end
      end
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :category_id).merge(author: current_user)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:f_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:f_name])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/_category.html.erb
<%= link_to category_transactions_path(category), class:"text-dark", style:"text-decoration: none;" do %>
  <div class="card flex-row align-items-center p-3 my-3 rounded-0">
    <div style="width: 5rem; height: 5rem; object-fit: cover; overflow: hidden;">
      <img src=<%= category.icon %> class="card-img-top" alt=<%= category.name %>>
    </div>
    <div class="card-body">
      <div class="d-flex justify-content-between">
        <h5 class="card-title"><%= category.name %></h5>
        <p class="card-text"><strong>$<%= category.category_total_amount %></strong></p>
      </div>
      <p class="position-relative" style="top: 1em"><%= category.updated_at.strftime('%A-%b-%Y | %H:%M:%S') %></p>
    </div>
  </div>
<% end %>

app/views/categories/index.html.erb
<h4 class="bg-success text-center text-white pb-2">Categories</h4>
<section>
  <div class="container mb-5">
    <%= render partial: "category", collection: @categories %>
  </div>
  <%= link_to "Add New Category", new_category_path, class:"btn btn-success rounded-0 w-100 position-fixed bottom-0" %>
</section>

app/views/categories/new.html.erb
<section>
  <h4 class="bg-success text-center text-white pb-2">Add new category</h4>
  <div class="container-fluid mt-3">
    <%= bootstrap_form_with model: category, url: categories_path(@category) do |f| %>
      <div class="field">
        <%= f.text_field :name, autofocus: true, class:"rounded-0", hide_label: true, placeholder: "Category Name", required: true %>
      </div>

      <div class="field">
        <%= f.text_field :icon, autofocus: true, class:"rounded-0", hide_label: true, placeholder: "Category Icon (icon link)", required: true %>
      </div>

      <div class="actions">
        <%= f.submit "Save", class:"btn btn-success rounded-0 w-100 position-fixed bottom-0 start-0" %>
      </div>
    <%end%>
  </div>
</section>

app/views/layouts/_nav.html.erb
<% if user_signed_in? %>
  <div class="bg-success text-white d-flex justify-content-between align-items-center container-fluid">
      <%= link_to categories_path, class:"text-white", style:"font-size: 1.8rem" do %>
        <%= fa_icon "arrow-left" %>
      <% end %>
      <%= button_to destroy_user_session_path, class:"btn btn-danger rounded-circle mt-2", :method => :delete do %>
        <span style="font-weight: bold">&#10555;</span>
      <% end %>
  </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-light">
    <%= render partial: "layouts/nav" %>
    <% if notice && notice.empty? %>
      <div class="alert alert-success" role="alert">
        <p class="notice"><%= notice %></p>
      </div>
    <% elsif alert && alert.empty?  %>
      <div class="alert alert-danger" role="alert">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/splash/index.html.erb
<section class="pt-5">
  <div class="container ">
    <div class="text-center">
        <h1>IN💲TANT BUDGET</h1>
        <p>Instant Budget provides track of daily transaction that helps make wise financial desicions</p>
    </div>
    <div class="mx-auto" style="width: 8rem; margin-top: 5em;">
      <%= link_to "Sign In", new_user_session_path, class:"btn btn-success mb-3 py-2 rounded-0", style:"width: 100%" %>
      <%= link_to "Sign Up", new_user_registration_path ,class:"btn btn-outline-dark py-2 rounded-0", style:"width: 100%" %>
    </div>
  </div>
</section>

app/views/transactions/_transaction.html.erb
<div class="card p-3 my-3 rounded-0">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <h5 class="card-title"><%= transaction.name %></h5>
      <p class="card-text"><strong>$<%= transaction.amount %></strong></p>
    </div>
    <p class="position-relative" style="top: 1em"><%= transaction.updated_at.strftime('%A-%b-%Y | %H:%M:%S') %></p>
  </div>
</div>

app/views/transactions/index.html.erb
<h4 class="bg-success text-center text-white pb-2"><%= @category.name %>: $<%= @category.category_total_amount %></h4>
</div>
<section>
  <div class="container mb-5">
    <%= render partial: "transaction", collection: @transactions %>
  </div>
  <%= link_to "Add New Transaction", new_transaction_path, class:"btn btn-success rounded-0 w-100 position-fixed bottom-0" %>
<section>

app/views/transactions/new.html.erb
<section>
  <h4 class="bg-success text-center text-white pb-2">Add new Transaction</h4>
  <div class="container-fluid mt-3">
    <%= bootstrap_form_with model: transaction, url: transactions_path do |f| %>
      <div class="field">
        <%= f.text_field :name, autofocus: true, class:"rounded-0", hide_label: true, placeholder: "Transaction Name", required: true %>
      </div>

      <div class="field">
        <%= f.number_field :amount, autofocus: true, class:"rounded-0", hide_label: true, step: "any", placeholder: "$0.00", required: true %>
      </div>
      <div class="field">
        <%= f.select :category_id, @categories.collect {|category| [category.name, category.id]}, class:"rounded-0", hide_label: true, required: true%>
      </div>

      <div class="actions" style="margin-top: 5em">
        <%= f.submit "Save", class:"btn btn-success rounded-0 w-100 position-absolute bottom-0 start-0" %>
      </div>
    <%end%>
  </div>
</section>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%# <%- if controller_name != 'sessions' %>
  <%# <%= link_to "Log in", new_session_path(resource_name) %><%# <br />
<%# <% end %>

<%# <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%# <%= link_to "Sign up", new_registration_path(resource_name)<br /> %>
<%# <% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <div class="d-flex justify-content-center">
  <%= link_to "Forgot your password?", new_password_path(resource_name), class:"text-dark mt-5" %><br />
  </div>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>